### ISSUE TITLE
Youtubeのアーカイブリンクを見るための開発

### ISSUE THREAD

**Issue by london-newyork** [three-ppp/PPP_Engibeer#16]
desktop-19 、29について、開発の内容を改めました。
仕様を確認したところ、Zoomとの連携ではなく、Youtubeのアーカイブリンクを見られるようにするということでした。

追記：

**放送終了ページ（ユーザー）**
画面
YouTubeアーカイブがiFrameで見られる。
投稿されたエンジビアとへぇ数が見られる。
　
**放送終了ページ（管理者）**
YouTubeリンク貼り付け前・YouTubeリンク貼り付け後
YouTubeアーカイブを設定・編集できる。
他はユーザーと同じ。

過去の当issueの投稿↓

(Zoom)APIで連携するものだと思います。
desktop-19 、29

仕様より抜粋　↓
> 本プロダクトはZoomと併用して用いられます。管理者（私）はZoomで司会進行し、エンジビア投稿者はZoomで画面共有して説の検証を行います。ユーザーは本プロダクトとZoomを同時に開きながら楽しむ想定です。

**Comment by rinka0v0** [comment]
自分はZoomの画面共有機能でブラウザで開いたエンジビアの泉を画面共有するという意味なのではと思いました。

**Comment by london-newyork** [comment]
APIを埋め込まなくてもいいっていう感じですかね・・？
間違ってたらごめんなさい、
りんかさんは、参加者個々にZoomをデスクトップ上にダウンロードしてきていることが前提条件で、個々のZoomアプリ上で管理者（しまぶーさん）の画面共有ができると言うことをおっしゃっていますか・・？

なんか自分は、こんな流れを想像していました・・

ZoomのAPI連携しているエンジビアの泉のアプリ上で、ユーザー、管理者がZoomの画面を開ける、、という感じなのかなと・・
例で言うと、QinのOviceでWEB会議システムを使ってるような感じなのかと・・Ovice内でWEB会議システムを呼び出し→Ovice内で通話できて画面がみられる→画面共有もできるみたいな感じなのかと・・

私もちょっと仕様の意図がよくわからないですね・・

**Comment by rinka0v0** [comment]
参加者個々にZoomをデスクトップ上にダウンロードしてきていることを前提条件として考えていました、すみません

**Comment by oshita-n** [comment]
@rinka0v0 https://github.com/three-ppp/PPP_Engibeer/pull/51　これで開発は終わっている感じでかね？
終わってたらクローズにした方が混乱しないかもですー

**Comment by oshita-n** [comment]
一応クローズにしときます。問題あったらオープンにしてください
