### ISSUE TITLE
レビューもらった部分を直す

### ISSUE THREAD

**Issue by rinka0v0** [three-ppp/PPP_Engibeer#58]
# 概要
Slackでレビューもらった部分をできるだけ直す。

# タスク
- 既存コードについて
■修正できるか試してほしいところ（多分なおせる）

- [x] _app.tsxのTailwindの読み込み部分

import "tailwindcss/tailwind.css";があるのであれば、global.cssの3行は不要なはずです:+1:
componentの2箇所でCSS Modulesを使用しているのにはなにか特別な理由がありますか？なければTailwind CSSで統一したほうが良いかと思います！
■改善点

- [x] constantsなどの名前の、定数用ディレクトリを作る

その中にAPIエンドポイントや、ルートなどを記述すると良いと思います。
APIはprocess.env.NODE_ENV の値で開発環境か本番環境かの切り替えができるので、APIエンドポイントなどの値はこの値によって自動的に切り替えると楽です！
ルートは const STATIC_ROUTES = { HOME: '/home' } as constなどすると型安全に扱えるのでおすすめです

- [x] ボタンがdisabledな際にonClickをundefinedにしている箇所

ここはわざわざonClickを無効にせずに、buttonタグ自体のdisabled属性をtrueにすると良いと思います。
CSSも、Tailwind CSSなのであればclassName="disabled:bg-gray-200"などのように、disabled時のクラス名も管理できます！

- [x] fetchの処理

fetchメソッドではなく、SWRなどのライブラリを使うのが良さそうです。（って思ったけど、Firebaseならそもそもfetchしない？）
fetch用のディレクトリを作り、外部データ取得用の関数をまとめたり、共通化すると良いと思います。
外部データの取得処理が見やすくなる
レスポンスの型やエラーの共通化
開発時と本番時の取得処理の違いを吸収できるため、呼び出し側で開発環境か本番環境か意識しなくて良くなる
などのメリットがあります

- [x] map時のkeyをindexにするの良くない（Zennの記事にいいのがある）

基本的にidなどの、その配列内で一意になる値があればそれを使うべきです。ないなら仕方なくindexという感じですね。

- [x] propsのユニオン型とかはtypesディレクトリ切って共通の型にしたい（共通化できそうな部分多々あり）

エンジビアのstatusは3種類の文字列でstatusを扱っていると思いますが、ここは絶対に共通化するべきです。
わからなそうであれば詳しく説明します:+1:

- [x] コンポーネントはdefault exportではなく、export const Hoge = () => {}のようにした

- [x] 型定義のArray<Engibeer>ではなくEngibeer[]のほうが見やすい気がします！

■個人的な意見

- [x] Next.jsをv12にしたい

Babelのプラグインを使用しているとSWCがまだ対応していないなどあるけど、そうでないなら上げたほうがよいです。
Docker使うメリット？？
フロントはNode.jsのバージョンの違いくらいだと思うので、わざわざDockerを使う必要あるのかなとおもいました！
Docker使わなくても起動できるので、好みではありそう
せっかくならDockerで使うNode.jsはv16系のほうが、String.prototype.replaceAll()とかあって良いと思います:バンザイ:
それと、Dockerを使うならdocker-compose upコマンド1発で、サーバー、モックなどすべて起動できるとおもうので、できればそうしたほうが楽になると思います！

- [x] pagesやcomponentsなどを、srcディレクトリ切ってまとめたい。ルート直下にフォルダが多くて少しみにくい。

- [ ] 時間的に厳しくないなら、linter, formatterをもっとガッツリ指定したほうがよさそう。しまぶーさんの設定コピペでよかったりする。

- [x] import時のパスは絶対パスのほうが見やすい

tsconfig.jsonのbaseUrlの指定でできたはず

- [x] propsはデストラクトせずにprops.hogeのように使いたい（完全に好み）

もしくはconst SampleComponent: VFC<{ hoge: string }> = ({ hgoe }) => {...}のように引数で受け取る段階でデストラクトもあり。ここはチームで見やすいように好きにして良いと思います。

- [ ] componentディレクトリの分け方をもう少しきれいにしたい

ひとつのディレクトリ内複数のコンポーネントがある場合に、index.tsとかつくってexport { Hoge } from "./Hoge"とすると、import時に複数行にならずに呼び出せます

- [ ] layoutコンポーネントはつくらない？？

- [ ] formの管理（inputタグなどの管理）はReactHookFormが便利です。TypeScriptにも対応しているし、採用しているところも多いと思うので、練習も含め入れてみるのをおすすめします。

- [x] typeのimportは個人的にimport type {} from ''を使うのが好きです:exceptionallyfastparrot:

- [x] （余談）VFCとFCの違い

これはかんたんで、props.childrenを持つかもたないか（VoidFunctionalComponentかFunctionalComponentかの違い）
VFCで定義してるのにわざわざ自分でPropsにchildrenを指定している箇所があるので、直したいですね:照れちゃう:
これ調べたのですが、VFCにして明示的にchildren指定したほうが良い説がある。もしかしたら自分の方がまちがってるかもしれない:ウケる:

**Comment by oshita-n** [comment]
このissueありがたい。。。
